### ISSUE TITLE
foo gallery doesn't work

### ISSUE THREAD

**Issue by avysfoto** [fooplugins/foogallery#101]
Hi! Foo Gallery doesn't work if I put 854 Images in it. Is it too much? It perfectly works if I take about 50 Images.
I work with PHP 7.0, Wordpress 4.6.1.

**Comment by bradvin** [comment]
Hi

There is no lazy loading OR pagination built into foogallery yet. Loading anything over 500 images would likely cause your browser to crash.

Pagination and lazy loading will be coming
