### ISSUE TITLE
A large number of queries to the database

### ISSUE THREAD

**Issue by helpmuw** [fooplugins/foogallery#102]
I installed the plugin Query Monitor. He has shown me clearly that the problem is in your plugin. He is doing a lot of queries to mysql database. I do not like it. Your plugin is very heavy !

http://clip2net.com/s/3FPLU7W - This is an example

Look here please. This way you should be? Or is it I have any problems with your plugin.

Your plug-in generates a request 202 from total 298 - http://clip2net.com/s/3FPMb3l

I have set php 7, MYSQL 5.7

**Comment by helpmuw** [comment]
And the answer is still no. And the problem is very serious!

**Comment by steveush** [comment]
Hi,

It's the holiday season and support is not guaranteed for this plugin as it is free. Brad, the developer, is currently away with his family, if you can't wait please feel free to uninstall it.

Regards

**Comment by helpmuw** [comment]
'll wait. The plugin is free - yes. But it does not work a paid version FooBox HTML & Media Lightbox and FooVideo without it. So you're saying this is incorrect.

**Comment by bradvin** [comment]
hi @helpmuw - How many images are in your gallery?

I tested FooGallery + Query Monitor with a gallery of 10 images and it generated 4 out of the total 36 queries to the database. A few questions to narrow down the problem so I can replicate on my end:

1) Are you using latest version of WP and FooGallery?
2) What gallery template are you using?
3) How many images in your gallery?
4) What is the output of your system info from FooGallery -> System Info
