### ISSUE TITLE
Add Gallery Description

### ISSUE THREAD

**Issue by thomaskonrad** [fooplugins/foogallery#105]
Hi,

is it possible to add a description to a gallery? My customer does not only want to add the title and the images, but also a short description of the gallery.

If not, can I somehow extend FooGallery so that it includes a Wordpress rich-text editor in the gallery edit form?

Thank you
Thomas

**Comment by bradvin** [comment]
The gallery is just a custom post type, so you could enable the text editor for the foogallery post type.
You would then need to either alter your gallery template to include this description, or hook into one of the custom actions and output the content
