### ISSUE TITLE
Inline Javascript

### ISSUE THREAD

**Issue by AvalancheDesign** [fooplugins/foogallery#109]
I've been using the Foo Gallery, and I've come across your plugin, FooBox Image Lightbox. On the surface, I enjoy your plugin, but what's preventing me from using your plugin on my sites is inline javascript code being directly placed on the page, and not inside a .js file.

`/* Run FooBox FREE (v1.2.22) */
(function( FOOBOX, $, undefined ) {
FOOBOX.o = {wordpress: { enabled: true }, excludes:'.fbx-link,.nofoobox,.nolightbox,a[href*="pinterest.com/pin/create/button/"]', affiliate : { enabled: false }};
FOOBOX.init = function() {
$(".fbx-link").removeClass("fbx-link");
$(".foogallery-container.foogallery-lightbox-foobox, .foogallery-container.foogallery-lightbox-foobox-free, .gallery, .wp-caption, a:has(img[class*=wp-image-]), .foobox").foobox(FOOBOX.o);
};
}( window.FOOBOX = window.FOOBOX || {}, FooBox.$ ));

FooBox.ready(function() {

jQuery("body").append("f");
FOOBOX.init();

});`

**Comment by bradvin** [comment]
The inline JS is generated based on the settings you choose for FooBox.
The 2 alernative options are:

1) generate the settings in json and push those to the front-end in a similar way.
2) generate a static JS file when settings are saved and include that. (This has obvious drawbacks : caching, file permissions etc)

We will likely go the route of option 1 in a future release, but to be honest it is very similar to just including inline JS as we do now, so the priority for making this change is not high at the moment. The only reason we were actually looking at doing this, was to get around an issue when plugins were deferring the loading of scripts on the page  causing foobox to stop working.

Your thoughts would be appreciated
