### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by primepassages** [fooplugins/foogallery#111]
I am testing FooGallery on my WP site. I created a gallery just fine but when I put the shortcode into a post and preview it doesn’t work — the shortcode just shows up as text in the post. Any thoughts on what am I doing wrong? Thanks!
![screenshot-primepassages com 2017-04-24 12-19-06](https://cloud.githubusercontent.com/assets/27972031/25353314/064185b2-28ec-11e7-8fd5-ea1c50210c97.png)

**Comment by Dollie662** [comment]
+ 1  -  I have the same issue.  Any advice?  Many thanks

**Comment by bradvin** [comment]
There should be no reason for the shortcode to not work, unless the plugin is deactivated.

Are you using any page builders?

**Comment by wavehamza** [comment]
I'm facing same issue today, the page builder i am using is Visual Composer.

![image](https://user-images.githubusercontent.com/24474473/99254872-575af300-2813-11eb-86d7-d435042db523.png)
