### ISSUE TITLE
Rogue right quote character

### ISSUE THREAD

**Issue by JulianKingman** [fooplugins/foogallery#112]
I'm pretty sure that somewhere in the scripts that load the templates there's a ” instead of a ", which caused some weird display issues where I had html characters inside of a `data` tag (which I've since done away with). I couldn't find it, but it may cause other problems for other people as well.

**Comment by bradvin** [comment]
Thanks for posting this, but I searched the plugin for the ” but none could be found. Which template were you using specifically? Perhaps the caption text was not being encoded?

**Comment by JulianKingman** [comment]
A custom gallery I developed. It's possible it was not being encoded, but I put some filters on it that should have done the encoding properly

**Comment by bradvin** [comment]
is the code hosted anywhere? I can have a look
