### ISSUE TITLE
Is there a way to display all images in one gallery, with album buttons, that show different images by different albums or categories?

### ISSUE THREAD

**Issue by aibo77** [fooplugins/foogallery#115]
Hello foogallery developers and users :)

I have a question:

Is there a way to show all images in one gallery, but assign different images to different albums or categories. then make a button for every album or category, and when you press a certain button, only images from that category show up. I saw this functionality in Sydney Theme's images section, and really like the idea of it, but I don't like how it's done in there, by making every picture a separate project, too much time consuming. You can see the functionality in this video https://www.youtube.com/watch?v=EpMp_6PSJXw&t=1038s @14:40min, I would like to recreate it with foogallery if possible :)

**Comment by bradvin** [comment]
Not at the moment, but we are busy with a new version of FooGallery that will include a gallery template that will give you a similar type of function
