### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by Dollie662** [fooplugins/foogallery#118]
Hi there!   I created a gallery but when I put the shortcode into a post and preview it doesn’t work — the post preview is blank. Any thoughts on what am I doing wrong? Thanks!

**Comment by Dollie662** [comment]
Here's the link to my post: http://oliviamarocco.com/2017/07/test-2-carousel/

**Comment by bradvin** [comment]
I see you are using the owl carousel template. Please can you change the gallery to the default responsive image gallery template, to see if the gallery at least shows.

We might also need to get the developer of the owl carousel template involved, as that is a 3rd party plugin

**Comment by Dollie662** [comment]
Hi Bradvin.   Thanks for your reply.   I've just tried with the default responsive image gallery and it works.  Same link : http://oliviamarocco.com/2017/07/test-2-carousel/

So the issue seems to be with Owl Carousel.  The reason I want to use Owl carousel is because it seems to offer a variable width carousel, for both portraits and landscape photos.

**Comment by bradvin** [comment]
The Owl Carousel template is a 3rd party plugin that is not developed by FooPlugins. You can create a new thread on their plugin page here : https://wordpress.org/plugins/foogallery-owl-carousel-template/
