### ISSUE TITLE
can't activate foogallery plugin

### ISSUE THREAD

**Issue by rfarf** [fooplugins/foogallery#122]
Installed fine, but throws error when you try to activate:
Fatal error: Uncaught Exception: trying to load "FooGallery_Simple_Portfolio_Gallery_Template" class that is not registered in config file. in /home2/iooedgmy/public_html/wp-content/plugins/portfolio-gallery/config.php:43 Stack trace: #0 [internal function]: portfolio_gallery_autoload('FooGallery_Simp...') #1 [internal function]: spl_autoload_call('FooGallery_Simp...') #2 /home2/iooedgmy/public_html/wp-content/plugins/foogallery/extensions/default-templates/simple-portfolio/class-simple-portfolio-gallery-template.php(3): class_exists('FooGallery_Simp...') #3 /home2/iooedgmy/public_html/wp-content/plugins/foogallery/extensions/default-templates/class-default-templates-extension.php(15): require_once('/home2/iooedgmy...') #4 /home2/iooedgmy/public_html/wp-content/plugins/foogallery/includes/includes.php(25): require_once('/home2/iooedgmy...') #5 /home2/iooedgmy/public_html/wp-content/plugins/foogallery/foogallery.php(94): require_once('/home2/iooedgmy...') #6 /home2/iooedgmy/public_html/wp-content/plugins/foogallery/foogall in /home2/iooedgmy/public_html/wp-content/plugins/portfolio-gallery/config.php on line 43

**Comment by rfarf** [comment]
Definitely unimpressed with "fooplugins" - the only support option they offer is this, and yet apparently no one monitors this forum... points off...

**Comment by bradvin** [comment]
@rfarf there seems to be a conflict between foogallery and another plugin you have activated called portfolio-gallery based on the stacktrace you provided (/home2/iooedgmy/public_html/wp-content/plugins/portfolio-gallery/)

Can you try and deactivate that plugin first before you activateFooGallery.

PLEASE NOTE : foogallery is a free plugin and support is not gaurenteed to be timely.

**Comment by bradvin** [comment]
I downloaded the plugin portfolio-gallery and had a look at the code. I found this in /portfolio-gallery/config.php:

`
	/**
	 * We do not touch classes that are not related to us
	 */
	if ( ! strstr( $classname, 'Portfolio_Gallery_' ) ) {
		return;
	}
`

Basically, they add a hook when new classes are instantiated globally, and do a check if the class name contains **Portfolio_Gallery_** which also applies to one of the classes inside FooGallery.

This is something that they should change on their end, as their code assumes there will not be any other plugins with similar class names. Clearly this is not the case, as FooGallery contains a similarly named class.

@rfarf - to get around this, you will def need to deactivate that plugin first

**Comment by rfarf** [comment]
Great, thank you very much - that was the problem.Steffen

**Comment by rfarf** [comment]
Got a response that fixed the problem, thank you.

**Comment by rfarf** [comment]
Nice plug-in, even the free version - thank you for making it!
