### ISSUE TITLE
[beta] Activating with existing gallery - gallery doesn't load, lightbox not working

### ISSUE THREAD

**Issue by awarner20** [fooplugins/foogallery#123]
Was running FooGallery v1.3.8 from the repo
FooBox PRO Settings - v2.4.0.0 (non-freemius)

I installed the beta and the page in which I had the existing gallery, then did not load the gallery. Just the horizontal loading bar icon would show.

I then went into edit mode for that gallery and clicked "Update", then reloaded the gallery page and it displayed the gallery as expected. So it seems Editing/Updating the gallery was necessary.

Also, FooBox was selected as the lightbox, but FooBox does not work on the gallery page.

[http://adamwwarner.com/gallery-one/](url)

**Comment by bradvin** [comment]
please download and test v1.3.13 which fixes your issues

If you want to test the upgrade again (as it only does it once per gallery) then you can install and activate the beta cleanup plugin from here : https://github.com/fooplugins/foogallery-beta-cleanup/archive/master.zip

Activate the cleanup plugin before you install and activate the latest beta of FooGallery
