### ISSUE TITLE
Masonry produces artifacts

### ISSUE THREAD

**Issue by ltsally** [fooplugins/foogallery#124]
Most of the images in masonry galleries  overlap. See http://www.pffla.org/foogallery-test/ 
![masonry beta v1 312](https://user-images.githubusercontent.com/23137886/29611246-241107f0-87fd-11e7-826a-96ea1084cd7d.jpg)

**Comment by bradvin** [comment]
Thanks for reporting this issue. It turned out to be a CSS conflict with your theme.
We have made some changes in the latest version 1.3.13 which fixes this issue.

Please download the latest and try again.
