### ISSUE TITLE
[beta v1.312] Issues

### ISSUE THREAD

**Issue by franskemper** [fooplugins/foogallery#128]
Thank you for the opportunity. After following instructions to the letters, I have the following comments:
1) Responsive Image Gallery. Space between thumbnails disappeared as well as shadow.
2) Image Viewer. Seems OK.
3) Justified Gallery. Images in thumbnails are distorted and stretched.
4) Masonry Image Gallery. Images in thumbnails are cut.
5) Simple Portfolio seems OK.
6) Single Thumbnail Gallery. Thumbnails do not appear stacked.
Feel free to examine at base.ftck.net
I'll leave it here for a while.
Best regards,
Frans Kemper

**Comment by bradvin** [comment]
Thanks for helping @franskemper 
I will go through your site and report back here

**Comment by bradvin** [comment]
hi @franskemper 

We have made some updates which should fix all of your issues. Please can you follow these steps:
Download the latest v1.3.15 from https://github.com/fooplugins/foogallery/archive/feature/gallery-template-client-rewrite.zip and override the old plugin.

Upload and activate the beta cleanup plugin : https://github.com/fooplugins/foogallery-beta-cleanup/archive/master.zip 

Visit the foogallery listings page and the galleries should be upgraded again with the correct values.
