### ISSUE TITLE
Masonry Layout

### ISSUE THREAD

**Issue by ltsally** [fooplugins/foogallery#129]
The images load correctly and the gallery is being properly centered.
However, none of the images shows up in the FooBox Pro popup on imahe click. See http://www.pffla.org/foogallery-test/ .

It would be great, if one could get rid of the white border and background for gallery images.

**Comment by bradvin** [comment]
Please can you test v1.3.14 to resolve the lightbox issue.

You can remove the white border, by choosing a border size of none on the appereance tab.
Do you not want to show a background at all while the images are loading? If so, then the loading icon will also not show. Is that acceptable?

**Comment by ltsally** [comment]
Hi Bradvin,

FooGallery v1.3.14 works perfectly with FooBox Pro!

There are still some things which I think do not work as they should or which might be enhanced.

1.	As I have seen, there are two themes available - light and dark. They produce an appropriate background (white or grey) while images are loading. Would it be possible to add a transparent background / theme so that the background would not be visible? (--> thema.jpg) or maybe tell the plugin not to render any background if the frame is set to “0”?
2.	Long texts make an image in some cases invisible (theme2.jpg). An option to cut the strings to a predefined length (not in FooBox!) might be helpful.
3.	Using presets make the text in some cases shoeing up displaced (goliath.jpg, zoe.jpg).
4.	I wonder if it might be possible to add an option to render texts under the images as MaxGalleria does in case of the masonry layout  (maxgalleria.jpg)

 

It would be great if you could give me some hints on how to manipulate the descriptions (and backgrounds on which they are rendered) via css.

 

Best regards,

Robert

 

Von: bradvin [mailto:notifications@github.com] 
Gesendet: Donnerstag, 24. August 2017 19:10
An: fooplugins/foogallery <foogallery@noreply.github.com>
Cc: ltsally <sally@e-lecture.org>; Author <author@noreply.github.com>
Betreff: Re: [fooplugins/foogallery] Masonry Layout (#129)

 

Please can you test v1.3.14 to resolve the lightbox issue.

You can remove the white border, by choosing a border size of none on the appereance tab.
Do you not want to show a background at all while the images are loading? If so, then the loading icon will also not show. Is that acceptable?

**Comment by steveush** [comment]
Hi @ltsally,

Unfortunately none of your images came through so I'll respond with what I think is going on but please correct me where wrong.

1. It would be possible however there would be an issue with the loading icons with a custom theme as they are gifs which do not support transparency and so they have a solid background where necessary. At the moment the light and dark theme each have there own corresponding color matched icons so a custom theme would need to implement this as well if it wanted to support all the icons. All the current loading icons were created using https://loading.io/ so creating your own with appropriate color schemes should be fairly straight forward. This is something I actually intend to add into the documentation, a section on how to create your own themes. I'll probably put together a basic theme you could just copy and manipulate to your liking as part of that documentation.
2. I'll look into this as it would resolve long content issues quite nicely.
3. Not 100% sure here without the image but the presets are definitely designed with a larger thumb in mind, something along the lines of 250x200 upwards. We could look at changing them to be a bit more friendly with smaller thumbs though by bringing down the font sizes and adjusting the position and transitions a bit.
4. Another one that I might be mistaken on without the image but I'm guessing it's just having the captions statically placed below the thumbs? I'll look into it and if implemented see if I can make it an extra option for captions alongside On Hover and Always Visible for templates that support it.

Thanks for the feedback.

**Comment by ltsally** [comment]
I could have adjusted some foo styles via CSS. Still need to get rid of the white/grey image placeholders while they are loading (or just make them transparent). Is it possible to do this with CSS?
The images I made and the actual problem visualize the pics from http://www.pffla.org/download/foo.rar 
The gallery itself can be found at:http://www.pffla.org/foogallery-test/

**Comment by steveush** [comment]
Hi @ltsally,

The placeholder white/grey is set by the following CSS:

```css
/* Idle / Loading / Error Style */
.foogallery.fg-light .fg-item.fg-idle,
.foogallery.fg-light .fg-item.fg-loading,
.foogallery.fg-light .fg-item.fg-error {
	background-color: #eee;
	box-shadow: inset 0 0 0 1px #ddd;
}
.foogallery.fg-dark .fg-item.fg-idle,
.foogallery.fg-dark .fg-item.fg-loading,
.foogallery.fg-dark .fg-item.fg-error {
	background-color: #444;
	box-shadow: inset 0 0 0 1px #333;
}
```

So you can override those values or remove as required in some custom CSS.

As for your other issues I've already created the options for the max length for the caption title and description so that is resolved but not yet released and I'm busy looking into #3 and #4 in your list at the moment.

Thanks

**Comment by ltsally** [comment]
Thank you Steve. I do appreciate your phatastic help and immediate response.
The CSS works great!
In the previous version there was an option to place an animation while the images were loading. Will this option still be available and customizable in the forthcoming release?

**Comment by steveush** [comment]
Hi @ltsally,

This option is still available under the Appearance tab of the template settings, you can choose a loading icon there, however as I mentioned in my previous replies there will be an issue as the loading icons depend on having a specific background color set as gifs do not support transparency. Doing the customization's the way you are at the moment I think the easiest way would be to set the loading icon to default and then override the gif it uses with the below CSS:

```css
.foogallery.fg-light.fg-loading-default .fg-item.fg-loading {
	background-image: url('../img/loading-default.gif');
}
.foogallery.fg-dark.fg-loading-default .fg-item.fg-loading {
	background-image: url('../img/loading-default-dark.gif');
}
```

This covers the gifs used for both the light and the dark theme, you only really need to override whichever you are currently using.

As for the actual gif you can use a site like https://loading.io/ to create one that matches your specific colors, upload it to your site and then replace the urls in the CSS to point to the new gif.

On a separate note I've noticed that the loaded effect in the Appearance tab is not being set correctly, it is still using the old CSS class name which is something we need to fix in the upgrade from the old to new version. Selecting a new value and then saving should override the old value and correct it allowing you to actually see the effect working.

Thanks

**Comment by ltsally** [comment]
I thought about an animation which shows up before all images have loaded.
I could do it in the previous plugin version using the following css:
`.foogallery-masonry-loading {
    background:  #4e000e url('http://www.pffla.org/wp-content/uploads/preloader/pffla-loading-dash-1.gif') no-repeat center center;
    margin-top:-20px;
}`

**Comment by steveush** [comment]
Ah OK, that at the moment is not available, the loading icon has been switched to the individual items rather than the entire gallery so users can see what is ready as it is loaded rather than having to wait for all images to be complete. The issue with the previous method was that sometimes a request for an image could just disappear into the void and the request would only error after a timeout period (usually 30 to 60 secs) and during this time all other items were hidden which gave the impression that everything was either working very slowly or is broken entirely. This way as it is handled individually you as a user should always have something to view and errors are easy to spot.

**Comment by ltsally** [comment]
OK. I am fine with it. Thanks again for your great support and all the enhancements of the plugin!

**Comment by ltsally** [comment]
Sorry - just one more question.
Would it be possible to implement picking up all images out of a specified directory rather, than selecting them one by one from the WP media gallery? I use Media Library Folders Pro from Maxgalleria but it does not seem to work correctly either with Divi nor with FooGallery media picker,

**Comment by bradvin** [comment]
@ltsally thanks for your help in testing. We really appreciate this type of feedback, as it makes us question why we made certain decisions.

Your suggestion to pull in images automatically from a folder has been asked for before and it is definately something I would like to implement in the near future. But at the moment, we really just want to focus on getting the new gallery templates 100%, so that is where our focus is.

**Comment by ltsally** [comment]
Awaiting the final release :)

**Comment by ltsally** [comment]
Dear Bradvin,

when will this final Foogallery version be released?

I use the beta version 1.3.15. The official release is 1.3.8.

Best,

Robert

**Comment by bradvin** [comment]
@ltsally we have made some more recent changes in V1.3.17

Please download and test a few things:
1) the different pagination options (some of these will only be available in PRO in the future)
2) test albums still function as before

**Comment by ltsally** [comment]
Could have only loaded the beta version 1.3.16.

Which is the actual plugin links?

All seems OK but the effect with captions shown prior displaying images is back.

Robert

 

Von: bradvin [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. September 2017 21:25
An: fooplugins/foogallery <foogallery@noreply.github.com>
Cc: ltsally <sally@e-lecture.org>; Mention <mention@noreply.github.com>
Betreff: Re: [fooplugins/foogallery] Masonry Layout (#129)

 

@ltsally <https://github.com/ltsally>  we have made some more recent changes in V1.3.17

Please download and test a few things:

1.	the different pagination options (some of these will only be available in PRO in the future)
2.	test albums still function as before

**Comment by bradvin** [comment]
please can you explain "captions shown prior displaying images" in a bit more details please

Again, thanks for your help in testing the beta

**Comment by ltsally** [comment]
See: 
![image](https://user-images.githubusercontent.com/23137886/30715273-004f5c1a-9f16-11e7-87b1-88430b92d3a7.png)

**Comment by steveush** [comment]
Hi @ltsally,

I've double checked your original link http://www.pffla.org/foogallery-test/ and I am not seeing the captions as in the above image. Could you make sure your browser cache etc. is cleared and check again on your side? I placed some breakpoints in the JS to halt the execution before anything is run and the captions are indeed hidden before the plugin is initialized, as it should be. My original CSS fix still seems to be intact and only allows the caption to be shown once an item is loaded.

Thanks

**Comment by ltsally** [comment]
Everything has been cleared.

I can still observe the problem from time to time. Not always. 

 

Von: steveush [mailto:notifications@github.com] 
Gesendet: Freitag, 22. September 2017 17:30
An: fooplugins/foogallery <foogallery@noreply.github.com>
Cc: ltsally <sally@e-lecture.org>; Mention <mention@noreply.github.com>
Betreff: Re: [fooplugins/foogallery] Masonry Layout (#129)

 

Hi @ltsally <https://github.com/ltsally> ,

I've double checked your original link http://www.pffla.org/foogallery-test/ and I am not seeing the captions as in the above image. Could you make sure your browser cache etc. is cleared and check again on your side? I placed some breakpoints in the JS to halt the execution before anything is run and the captions are indeed hidden before the plugin is initialized, as it should be. My original CSS fix still seems to be intact and only allows the caption to be shown once an item is loaded.

Thanks

**Comment by ltsally** [comment]
Here is what I get
http://www.pffla.org/download/effect.mp4

**Comment by steveush** [comment]
Hi @ltsally,

I think I've found the issue, the FooGallery stylesheet is being included in the footer along with its' JavaScript files, this is something we will need to change so they are included in the `<head/>` along with the rest of the CSS. The flash we are seeing is because the page renders top down, so the captions are visible until the stylesheet is loaded by the browser which then subsequently hides them. I noticed in the video that you clicked the `FooGallery-Test` link at the top of the gallery to reload it, I was only able to reproduce the flash when clicking on this as well so thanks for that.

Thanks

**Comment by ltsally** [comment]
Hi,
just wanted to know if the problems I reported about have been solved. Got a message to upgade the foogallery to the pro version within the site but there is no information available on the version, features (what is the difference between the free and the pro plugin version).

**Comment by bradvin** [comment]
@ltsally pls download and install the latest beta version 1.3.23 and your issues should be resolved. Please can you test and let us know

**Comment by ltsally** [comment]
I have isntalled the latest client rewrite 1.3.23 version but the images do not show up mow at all:  http://www.pffla.org/foogallery-test/

**Comment by ltsally** [comment]
Sorry - it is already 1.3.24 from GitHub.

**Comment by ltsally** [comment]
..

**Comment by ltsally** [comment]
It looks like the newest version 1.3.25 works perfectly again!

**Comment by ltsally** [comment]
The effect reported on 21. Sept. inst in version 1.2.28 back again :(

**Comment by ltsally** [comment]
Not sure if this means something. The error shows once only and after then everything is Ok.
![image](https://user-images.githubusercontent.com/23137886/32914351-8f337c9c-cb15-11e7-9099-5548ac05ec16.png)
