### ISSUE TITLE
Foo Masonry  - loading effect

### ISSUE THREAD

**Issue by ltsally** [fooplugins/foogallery#130]
Is it possible to supress showing up titles and descriptions while a masonry gallery is loading and no images are visible yet? You can see the effect in http://www.pffla.org/download/foo-masonry-loading-effect.rar (latest FooGallery beta)

**Comment by steveush** [comment]
Hi @ltsally,

They should be hidden by default and only shown when loaded so I'll take a look at your site for any conflicts with the theme that I need to account for. I see this is visible on your original url http://www.pffla.org/foogallery-test/ so I'll debug using that.

Thanks
