### ISSUE TITLE
Gallery extension broken in version 1.3.29

### ISSUE THREAD

**Issue by maynardsmith** [fooplugins/foogallery#132]
I have a site using FooGallery and a custom extension that I wrote to provide a particular Gallery style that our site wanted as a default.  With the update to 1.3.29 this is now broken, and gives the following error message when loading a page containing this gallery.

Fatal error: Call to undefined function foogallery_enqueue_imagesloaded_script() in /home/hitchinc/dev_site/wp-content/plugins/foogallery-hccgallery/foogallery-hccgallery-extension.php on line 361

The API for extensions appears to have changed, or not to be working correctly.  Please advise.

With thanks, Tony

**Comment by bradvin** [comment]
hi Tony,

Please can you edit your gallery template and replace the usage of the function foogallery_enqueue_imagesloaded_script and rather use the following code:

`wp_enqueue_script('imagesloaded');`

Sorry for the inconvenience
