### ISSUE TITLE
Something is wrong with your website

### ISSUE THREAD

**Issue by jjlpdx** [fooplugins/foogallery#135]
I was finally going to download/install foo gallery today, but there is something seriously wrong with your website - it appears to be essentially dead. All urls just result in a blank download file - download.htm, or an error. Perhaps you're just working on it? bad timing for me though... I finally have some time to work on this, and just totally stuck. :-(

**Comment by bradvin** [comment]
sorry you are having issues with the website. Can you share the URL domain that the download is using? Is it foo.gallery or freemius.com?

Please mail me brad @ fooplugins . com and send me the domain and email address you are using FooGallery on and I can send you the plugin file directly
