### ISSUE TITLE
Activation Error 

### ISSUE THREAD

**Issue by rubenmarin** [fooplugins/foogallery#138]
Upon activation i get the following errors.

Notice: Undefined offset: 891835 in /wp-content/plugins/foogallery/freemius/includes/class-freemius.php on line 8264
Fatal error: __clone method called on non-object in /wp-content/plugins/foogallery/freemius/includes/class-freemius.php on line 8264

is there a php version requirement ?

Tested on php version :  5.4.16

**Comment by bradvin** [comment]
please follow this guide to help you with the fatal error you are getting : http://fooplugins.helpscoutdocs.com/article/120-freemius-errors

**Comment by rubenmarin** [comment]
Thank you @bradvin that did the trick.
