### ISSUE TITLE
Mixing of Video and Images

### ISSUE THREAD

**Issue by CarlaMck77** [fooplugins/foogallery#139]
I saw a tutorial online that stated I could add video and images to the same gallery and I was able to add video, however on the front-end of the website, when I click on the video, it appears in a new tab. How would I be able to let the video appear in a pop up as it does for the images? Would really appreciate an urgent response. (Wordpress)

**Comment by bradvin** [comment]
A few questions:

What URL is your gallery?
What version of FooBox, FooGallery and FooVideo are you using?

**Comment by Carlitta87** [comment]
This is the url: https://tinyurl.com/y87ggq4a
FooBox Image Lightbox (Version 1.2.27), FooGallery (Version 1.4.8) and FooVideo (Version 1.0.25)
