### ISSUE TITLE
All-In-One Stack Album template doesn't work with Responsive Lightbox by dFactory

### ISSUE THREAD

**Issue by viglia** [fooplugins/foogallery#141]
The Lightbox "Responsive Lightbox by dFactory" does not work when selected in the Album settings.

The reason is (I point to that in the link below) that the "rel" attribute does not contain the value "lightbox" but the gallery ID.

Since it's the first time I approach this plugin I don't know if this is for some reason wanted or if it is a bug. Can we just replace gallery[galleryID] with lightbox?

Ps. just adding a second value to the rel attribute does not solve the problem. It should be completely replaced with just lightbox.

https://github.com/fooplugins/foogallery/blob/44840f458e104715770742351b045a4aa59f96d9/extensions/albums/album-stack.php#L17

**Comment by bradvin** [comment]
This has been fixed in the latest develop branch v1.4.27

Can you test it out please?

**Comment by viglia** [comment]
Fixed
