### ISSUE TITLE
Some gallery images loading fine on Desktops but not mobile / laptops...?

### ISSUE THREAD

**Issue by rothwellgroup** [fooplugins/foogallery#142]
Hi guys, love the plugin, but we've noticed on a client build site that many galleries are not loading on Macbook Airs (for example) or mobiles, but are loading fine on desktop computers. 

While the desktop user sees lovely images, the mobiles / smaller (less powerful perhaps?) devices see just placeholder images. 

In testing, we discovered image width may play a part - our current images are 1440px wide. When we recreate a gallery with images which are 1200px wide, the galleries load fine.

Yes, these images are big!!! The client is a prominent supplier of high quality building materials and wants to demonstrate the quality best he can.

So my question is - is there a known "maximum width" or size for the images to function correctly?

Many thanks
Glen

**Comment by rothwellgroup** [comment]
Just a thought - I realised we'd also enabled all retina views. I'll play with those settings while waiting for your response :)

Thanks
Glen

**Comment by rothwellgroup** [comment]
BINGO - I turned off all Retina options and the images load fine again. I'm guessing this is because we haven't supplied all the right file size options to suit Retina settings... I'll have to re-read the documentation!

**Comment by steveush** [comment]
Hi,

I haven't looked into this but just wanted to point out that you might be
hitting the maximum allowed image size on the devices. Take a look at this
blog
<http://www.williammalone.com/articles/html5-javascript-ios-maximum-image-size/>
post which is a bit outdated but explains the issue quite nicely. With
retina disabled your images would be always be displayed at 1440px but with
retina enabled that size is doubled (2880px), tripled (4320px) or
quadrupled (5760px) depending on the devices pixel density. These larger
sizes are more than likely being rejected by the device and so the
placeholder images are displayed. This is something to keep in mind when
creating the images for the gallery.

Thanks

**Comment by rothwellgroup** [comment]
Thanks mate, that's what I realised... yes the images would've been massive
:)

Cheers.
