### ISSUE TITLE
Performance and behavior

### ISSUE THREAD

**Issue by Campervita** [fooplugins/foogallery#148]
When using several galleries in a post, loading can take ages. Secondly, after the last image of a gallery it jumps to the next gallery of the post. Instead it should either jump back to the first image of the gallery or back to the text where the gallery is placed. Are these problems solved in the pro-version? If the answer is yes, I will buy it.  Do you need an example? Checkout this: https://campervita.com/die-burgenstrasse-2018/

**Comment by rbrenton** [comment]
Facing the same issues on a client website, coincidentally also RV related.
