### ISSUE TITLE
FooGallery get wp_query to work

### ISSUE THREAD

**Issue by liderbudowlany** [fooplugins/foogallery#151]
Hi, I using FooGallery and it's great plugin for my gallery, but I want to include a 10 last elements in gallery to homepage in slider, so I don't wan't to use foogallery shortcodes, because they don't support things, which I want to use, so I only want to get last 10 images src, only this, but I don't know how to reach that.

So for example I have this:

`$query = new WP_Query( array( 'post_type' => 'foogallery', 'p' => 123, 'posts_per_page' => 10 ) );
if ( $query->have_posts() ) :
	while ( $query->have_posts() ) : $query->the_post();
		// Which code should I use to reach single image src?
	endwhile;
endif;`

**Comment by bradvin** [comment]
you can use the limit attribute in the shortcode and make sure the gallery is ordered by date descending

e.g.

[foogallery id="123" limit="10"]
