### ISSUE TITLE
one of album has error and can't edit and show

### ISSUE THREAD

**Issue by pouriyaGhasemi** [fooplugins/foogallery#153]
hi, thank you for your time.
i can't understand why one of album has error and i can't edit or use it
but the other one is correct and i can edit and it show on web site
[its correct](http://linzisfilmfestival.com/opening/)
[it has error](http://linzisfilmfestival.com/filmmakers/)

**Comment by pouriyaGhasemi** [comment]
in which table data saved?
i found posts and postmeta related to gallery. but i think that its not all of data.
if i now i can compare records of correct and incorrect gallery

**Comment by bradvin** [comment]
Hi

I had a look at your pages. The page with the error is not loading at all. Can you try remove the foogallery shortcode from that page to see if the page loads.

The gallery data is saved in thje posts table as a post type foogallery and the post meta is saved against that post with all the info

**Comment by pouriyaGhasemi** [comment]
thank you.
actually i can't edit incorrect gallery from wp admin => foogallery => albums
but i can edit the correct album from wp admin => foogallery => albums
so its not about page.
so i should check database then answer again

**Comment by pouriyaGhasemi** [comment]
i think i find the bug.
i have a page with name "Filmmakers"
and a gallery with name "Filmmakers"
so i find that i can't edit page with name "Filmmakers".
i edit the real page (not gallery) and set post_title and post_name to new one
but still i can't edit the page and i can't edit the gallery
please help me @bradvin
