### ISSUE TITLE
Descriptions cut off on mobile devices

### ISSUE THREAD

**Issue by martinzoller** [fooplugins/foogallery#154]
This bug affects the "Simple Portfolio" gallery type.

It appears that the gallery items don't scale down correctly when the preview image is wider than the screen (i.e. on a mobile device). The image itself is scaled correctly, but the description text is cut off.

I did not look into the JavaScript code, but I suppose the problem might be that the "fg-item" frames are preloaded at full width, then a fixed height is calculated, and only after that, the items are inserted into the page, thereby being reduced in size.

I think the solution would be to refrain from setting a fixed height for each picture frame, and to let the text determine the height instead.

**Comment by bradvin** [comment]
thanks for reporting this - we will investigate further
