### ISSUE TITLE
Simple portfolio images are not shown when height is not set

### ISSUE THREAD

**Issue by jannisveerkamp** [fooplugins/foogallery#168]
A friend updated Foogallery (not sure from which version)

He uses `simple portfolio` and have only the height set for the images. The Width is left empty so it should determine itself. The images are not shown at all anymore.

It works when he only sets the width (and no height) or both. It also works for all the other types.

**Comment by bradvin** [comment]
hi @jannisveerkamp 

For Simple Portfolio, you need to provide both a width and height so that the cropping can work correctly
