### ISSUE TITLE
Deprecated filter notice in AIOSEO v4.0.0

### ISSUE THREAD

**Issue by arnaudbroes** [fooplugins/foogallery#172]
One of our customers reported that AIOSEO v4.0.0 is displaying a notice because FooGallery is using a deprecated filter (aiosp_sitemap_prio_item_filter) we removed in v4.0.0. 

Our free 4.0.0 version isn't out yet, but I already wanted to give you guys a heads up that we've deleted this filter, in case you want to add this functionality for our new version.

Feel free to reach out to me at abroes[at]awesomemotive.com and we can work together on a "fix" with backward compatibility for the old version of the plugin.

**Comment by bradvin** [comment]
thanks for getting in touch @arnaudbroes 

I have sent you an email to get more info

**Comment by bradvin** [comment]
this has been fixed and is included in the latest update
