### ISSUE TITLE
FooGallery Albums Extension is breaking Homepage Canonical

### ISSUE THREAD

**Issue by ShoGinn** [fooplugins/foogallery#178]
When using Albums, the redirect rules for the home page are not followed.

Ex. https://www.site.com doesn't get 301 redirected to https://site.com

Disabling the Albums extension fixes the problem.

Another fix I found was this webpage: https://ithoughtyoucouldusethis.com/fix-foogallery-albums-extension-breaking-homepage-canonical/

Which using your functions.php:

```php
function foogallery_canonical_fix()
{
    global $wp_filter;
    if (isset($wp_filter["redirect_canonical"][10])) {
        foreach ($wp_filter["redirect_canonical"][10] as $key => $hook) {
            if ($hook["function"][1] == "disable_canonical_redirect_for_front_page") {
                unset($wp_filter["redirect_canonical"]->callbacks[10][$key]);
            }
        }
    }
}
add_action('wp', 'foogallery_canonical_fix');
```

I am not a php coder so I don't have a fix. But I see the code is there, just not hooked?

**Comment by bradvin** [comment]
thanks @ShoGinn 

I will investigate this for a future release
