### ISSUE TITLE
Albums redirects to new album page

### ISSUE THREAD

**Issue by xpowert** [fooplugins/foogallery#221]
I displayed galleries as albums in the front page section, but when you click on a specific gallery, it redirects back to front page with opened gallery images. 
Is there a way to redirect it to the new gallery page, instead of frontpage?

**Comment by bradvin** [comment]
hi @xpowert 

When editing an album, change the "Gallery Link" setting to "Custom URL".

Then when hovering over the gallery, click the "i" icon which pops up a modal for editing gallery details. Enter the URL to your gallery page under "Custom URL" and click "Save Gallery Details".

Your album should now redirect to the gallery pages you entered in the custom URL for each gallery
