### ISSUE TITLE
Drag n Drop reordering of images and galleries issue

### ISSUE THREAD

**Issue by vasipani** [fooplugins/foogallery#48]
This is what happens every time i try to reorder my pics.... any idea how can i fix it?

![2015-04-04 11 22 20](https://cloud.githubusercontent.com/assets/11800696/6994444/a09e2a12-db22-11e4-8f2a-2a21f40ed7d3.png)

**Comment by bradvin** [comment]
It looks like some CSS padding or margins causing the problem. Chrome for Mac right? I will test it out on that browser and see what the problem is

**Comment by vasipani** [comment]
Yes chrome for mac... I also tried from another pc and some of the galleries allowed me to reorder... Some again not.. Great, i will wait for your reply!
Many thanks!

Στάλθηκε από το iPhone μου

6 Απρ 2015, 5:09 μ.μ., ο/η bradvin <notifications@github.com> έγραψε:
