### ISSUE TITLE
Gallery shortcode only

### ISSUE THREAD

**Issue by JonnyTech** [fooplugins/foogallery#50]
Is it possible to have just a shortcode without creating a gallery?

Natively Wordpress can do something like this:

[gallery link="file" _orderbyfield="menu_order ID" columns="4" _orderByField="menu_order ID" orderby="rand" ids="11,12,13,14,15,16"]

Can foogallery do something similar, ie:

[foogallery ids="11,12,13,14,15,16" template="responsive" value1="data1" value2="data2"]

Rather than have to use the new gallery editor in the dashboard?

**Comment by rumspeed** [comment]
+1 for me as well. I'd like to know the answer to that. :)

**Comment by bradvin** [comment]
This is not built in at the moment, but should be possible with some changes
