### ISSUE TITLE
Display all images, sorted by galleries

### ISSUE THREAD

**Issue by ffranke** [fooplugins/foogallery#54]
Dear Foodevelopers,

Is it possible to list all images on one page, structured by the gallery titles, something like that:

TITLE GALLERY 1
img_1, img_2, img3...

TITLE GALLERY 2
img_1, img_2, img3...

TITLE GALLERY 3
img_1, img_2, img3...

and so on...

I'm grateful for any hint in the right direction. I guess I have to loop through each gallery manual, right?

Thanks!
florian

**Comment by bradvin** [comment]
Hi there - I think what you are looking for is an album template. You might need to create a custom album template, but that is very easy to do. Do you want it to look like the default gallery template, but just show all galleries one after each other?

**Comment by ffranke** [comment]
Hi Bradvin,

thanks for your quick reply.
Ah ok, great. Yeah, all galleries one after another, displaying all images + Lightbox, would be great. 
Is there some documentation regarding custom album templates?

Is it also possible to auto-add galleries to this album? I need to keep the required steps for my editors as minimum as possible ;)

Thanks!
florian

**Comment by bradvin** [comment]
The best thing to do is check out the default albums and galleries. I have tried to keep things as simple as possible. As for auto-adding all galleries to an album, you can just use the `foogallery_get_All_galleries` function - https://github.com/fooplugins/foogallery/blob/master/includes/functions.php#L250
