### ISSUE TITLE
"foogallery_load_template" action is never fired

### ISSUE THREAD

**Issue by jmotes** [fooplugins/foogallery#55]
The "handle_lightbox_field" function in includes/public/class-shortcodes.php is tied to the "foogallery_load_template" action which in turn is supposed to trigger "foogallery_template_lightbox-{$lightbox}". The lightbox extension generated base code listens for "foogallery_template_lightbox-{$lightbox}" before enqueuing scripts. However, there is no corresponding do_action for "foogallery_load_template" anywhere in the foogallery plugin to get things moving, so that means scripts for lightbox extensions never get enqueued.

**Comment by jmotes** [comment]
If anyone else is having the same issue, here is the workaround I'm using in my lightbox extension:

```php
//replace this:
add_action( 'foogallery_template_lightbox-photoswipe', array($this, 'add_required_files') );

//with this:
add_action( "foogallery_loaded_template", array( $this, 'add_required_files' ) );

//then add a check for the correct lightbox in the add_required_files method:
function add_required_files() {

	$lightbox = foogallery_gallery_template_setting( 'lightbox' );

	if ( 'photoswipe' !== $lightbox ) {
		return;
	}

	//enqueue scripts/styles here
}
```
You could probably do the same check within a "wp_enqueue_scripts" action, but the foogallery lightbox data may not be available there.

**Comment by jmotes** [comment]
@bradvin Could you look into this issue please? My workaround is causing styles to be enqueued in the footer, resulting in validation errors.

**Comment by bradvin** [comment]
@jmotes please check the develop branch. I have added support for the lightbox action 'foogallery_template_lightbox-yourlightbox' and I have also included a function which allows you to enqueue stylesheets that will be appended in the head on the next page load, foogallery_enqueue_style
