### ISSUE TITLE
Increasing thumbnail size leads to ugly pixellated thumbnails

### ISSUE THREAD

**Issue by boyke** [fooplugins/foogallery#59]
Hi,

First of all i would like to say i love the plugin! What a relief if you are used to work with NextGen.

I'm now trying to increate the thumbnail size from 150 to 200. After that i get ugly pixellated thumbnails. What i already tried is 'clear thumbnail cache' and 'clear css optimization cache'.

I hope we can solve this problem (together). Thanks in advance.

Kind regards,

Boy

**Comment by bradvin** [comment]
please check the settings page to see what the thumbnail quality is set to.

**Comment by boyke** [comment]
It is set to 80

**Comment by bradvin** [comment]
Hi Boy,

I have built in extra steps around jpeg quality - you can test this out in the latest develop branch - https://github.com/fooplugins/foogallery/archive/develop.zip

Let me know if that solves your problem

**Comment by boyke** [comment]
I've set 'Thumbnail JPEG Quality' to 100 which seems to have solved the problem. Thanks in advance!
