### ISSUE TITLE
Loop of Gallery 'Attachments'

### ISSUE THREAD

**Issue by matrixltd** [fooplugins/foogallery#61]
Hi, I am attempting to display 3 images from a foogallery outside of the standard foogallery shortcode.

I am able to display all images 'attached' to a foogallery with this:

<?php 
$args = array(
			'post_type' => 'attachment',
			'posts_per_page' => 3,
			'post_parent' => $atts['id'], /// the id of the foogallery post
			'exclude'     => get_post_thumbnail_id()
		); ?>
<?php $attachments = get_children( $args );
if ( $attachments ) {
			foreach ( $attachments as $attachment ) {
				
				/// individual item code here
			}
	}
?>

However this only works for images directly uploaded (and therefore attached) to a particular foogallery post. This won't work for images 'selected in the media library' to be added to a foogallery as they do not have the required 'post_parent'.

**Comment by bradvin** [comment]
You cannot rely on `get_children` for the reason you state.

Load a FooGallery instance:

`$gallery = FooGallery::get_by_id( $gallery_id );`

And then you can loop through the attachments:

`foreach ( $gallery->attachments() as $attachment ) {`

You could then keep a count of the attachments you go through and break out after 3

**Comment by matrixltd** [comment]
That's perfect, just what i needed, thank you. Great plugin, and great support.

**Comment by lsterling03** [comment]
I'm trying to do this but can't seem to get it to work. I loaded the instance like so:

$gallery_id = 457
$gallery = FooGallery::get_by_id( $gallery_id );

But the foreach loop returns nothing. When I do a var_dump of $gallery, I see the correct gallery object, but the attachment_ids array is "0". Do you know what would account for that? I confirmed there are indeed photos in that FooGallery.

Thanks for any advice!
