### ISSUE TITLE
Foo gallery Prevents Unyson from loading extensions

### ISSUE THREAD

**Issue by WWS1** [fooplugins/foogallery#62]
when foo Gallery is installed it prevents the download of Unyson Extensions once Foo Gallery is deactivated Unyson Extensions can be downloaded

**Comment by bradvin** [comment]
not sure what Unyson is?

**Comment by WWS1** [comment]
Hi,

 

Unyson Is a drag and drop framework plugin for WordPress here is the WordPress plugin page https://wordpress.org/plugins/unyson/ and this is their web address http://unyson.io/ When the Foo Gallery is activated in the WordPress plugins and Unyson is also being used it is not possible to download the unyson extensions it produces an error message but if Foo Gallery is deactivated Unyson loads correctly.

 

Thanks

 

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by WWS1** [comment]
Forgot to send link for unyson on github here it is https://github.com/ThemeFuse/Unyson/blob/master/CONTRIBUTING.md

 

 

Best regards

Graham Savine-Jones

 

Tel: 01952 246557

www.wwswebservices.co.uk <http://www.wwswebservices.co.uk.co.uk/> 

 

 

This message and any attachments are confidential and should only be read by those to whom they are addressed. If you are not the intended recipient, please contact us, delete the message from your computer and destroy any copies. Any distribution or copying without our prior permission is prohibited.

Internet communications are not always secure and therefore we do not accept legal responsibility for this message. The recipient is responsible for verifying its authenticity before acting on the contents. Any views or opinions presented are solely those of the author and do not necessarily represent those of our company.

P Please consider the environment before printing this e-mail

**Comment by moldcraft** [comment]
Hello,

The problem is [this redirect](https://github.com/fooplugins/foogallery/blob/1.2.9/includes/admin/class-extensions.php#L34-L74).

![](https://static.md/cc1339f0da62dc7a8cd3051386b58a4d.png)

**How to reproduce**: [Install and activate Unyson](https://wordpress.org/plugins/unyson/) got to Unyson menu and try to install an extension.

**Comment by bradvin** [comment]
ok i see what is going on here now - both unyson and foogallery use the same query args "extension" and "action". I am going to rename the foogallery query arg to "foo_extension"

**Comment by bradvin** [comment]
please try the branch https://github.com/fooplugins/foogallery/archive/hotfix/unyson-support.zip which fixes the issue with unyson - I have tested it locally and all seems fine

**Comment by moldcraft** [comment]
Works. Thank you!
