### ISSUE TITLE
/gallery redirects to hompage after installing/deactivating FooGallery plugin

### ISSUE THREAD

**Issue by ballion** [fooplugins/foogallery#64]
I'm having a major issue with foogallery. 

On my website we have a gallery set up with NextGen Gallery (at website.com/gallery) and because I was not satisfied with NG I decided to give FooGallery a try. I had both Albums and Importer extensions active. 

Importing images from the existing NG Gallery was no issue at all, except I noticed when trying to import albums that FooGallery doesn't support nested albums (yet) which effectively makes it useless for me for the time being. So I deactivated to plugin for now.

When I had a look at website.com/gallery later it redirected me to the homepage at website.com. Normally this page should display the NG Gallery page I have set up there. It seems to be an issue with the slug /gallery because I duplicated my gallery page renaming it /galleries and it worked fine displaying my NG Gallery usual.

This is quite an urgent issue and any help/solution would be appreciated!

**Comment by bradvin** [comment]
The gallery slug is added by the albums extension, so decativate the albums extension if you are not going to use it.

You then need to flush your rewrite rules. You can do this by going to settings -> permalinks and saving.

For future:
The latest develop branch introduces a new setting under FooGallery -> Settings -> Albums tab that allows you to set the "gallery" slug to something else. If you change that you will also need to flush your rewrite rules again
