### ISSUE TITLE
Creating my lightbox extension

### ISSUE THREAD

**Issue by PedroMSimoes** [fooplugins/foogallery#65]
Well the problem is, i created a lightbox extension to work with foogallery and i can´t find where and how i  can make my extension appear in the lightbox dropdown in foogallery settings.
Your templates work only with the FooBox or it's possible to create on our lightbox extension(kinda like foobox) and make it work it the foogallery?

**Comment by bradvin** [comment]
you need to hook into the following filter:

`add_filter( 'foogallery_gallery_template_field_lightboxes', array($this, 'add_lightbox') );`

and then add your lightbox:

`		function add_lightbox($lightboxes) {
			$lightboxes['foobox-free'] = __( 'FooBox Free', 'foobox-image-lightbox' );
			return $lightboxes;
		}`

**Comment by PedroMSimoes** [comment]
Thanks for the quick answer,

Ye i already have that. 

`function __construct() {
                add_filter( 'foogallery_gallery_template_field_lightboxes', array($this, 'add_lightbox') );
        }

        function add_lightbox($lightboxes) {
            $lightboxes['my_extension_directory'] = __( 'Name', 'my-extension-directory/file' );
            return $lightboxes;
        }`

Is that what is needed? I replaced the "strings" needed in the function add_lightbox to what i thinks its needed to write. Can you confirm?

**Comment by bradvin** [comment]
I am not sure 'my_extension_directory' is correct. Surely it should be the name of your lightbox? So, 'prettyphoto' for example? It is the key that will be used in the classname that is generated to the front end. When the gallery is output to the front-end, the container will include a new class 'foogallery-lightbox-{key}'. E.g  'foogallery-lightbox-prettyphoto'.

And the localization domain string should be your plugin slug. So not 'my-extension-directory/file' but rather 'my-extension-slug'

Other than those changes, that is all you really need.

**Comment by PedroMSimoes** [comment]
Ok thks for the help. I will try fix it, i think that i alredy got the solution. So thanks for the help
