### ISSUE TITLE
Suggestion: user roles

### ISSUE THREAD

**Issue by JesseVelden** [fooplugins/foogallery#66]
Hello there!
I would like to see an option to use Wordpress' user roles (https://codex.wordpress.org/Roles_and_Capabilities) to set if certain roles can access the different admin pages.

**Comment by bradvin** [comment]
I like this idea - I will start adding this into 1.2.11

**Comment by peterampazzo** [comment]
@bradvin does this feature exist?

**Comment by iSWORD** [comment]
did this ever make it to production?

**Comment by bradvin** [comment]
this was never done, and is something that will be added in the future.
Can you explain your use-case in more detail please so I can understand why you need this?

**Comment by iSWORD** [comment]
I'll make a PR of exactly what I have in mind when I get some free time. I got over this using [Admin Menu Editor](https://wordpress.org/plugins/admin-menu-editor/) for now, but would like to have a cleaner way.

**Comment by waynemichel** [comment]
I would like to add my 2 cents worth.

I also require users with roles other than the admin to be able use the gallery, eg Shop Owner or Editor, etc
