### ISSUE TITLE
Enhancement: Use already existing thumbs

### ISSUE THREAD

**Issue by DennisGaida** [fooplugins/foogallery#67]
Love FooGallery, I would love it even more with the following enhancement:
I want to make use of Justified Gallery's automatic upscaling of thumbnails (`sizeRangeSuffixes` option). This way I could have small thumbs initially and Justified Gallery would load larger thumbs afterwards (http://miromannino.github.io/Justified-Gallery/performance-tips/). This would really enhance page load time for larger/multiple galleries on one page - basically a type of lazy loading.

Currently this is not possible as FooGallery is creating its own thumbs in its own folders (I can't just add the suffix as the other sizes don't exist). For all the images I already have multiple thumbs in the uploads folder at their original location and I would love to use those instead of the FooGallery thumbs. I would just replicate the already existing WP image sizes as my `sizeRangeSuffixes` in Justified Gallery and the rest would be automatic.

I actually found another plugin which works around exactly this issue with Justified Gallery & Wordpress, just with another wrapper plugin (Advanced Custom Fields): https://github.com/tmconnect/ACF-Justified-Image-Grid

**Comment by bradvin** [comment]
I think this would be a good idea to add. I had a look at the ACF-jig repo to see how they implement the sizeRangeSuffixes code, but I could not find anything related. Can you please help me by pointing out how they implemented sizeRangeSuffixes option using the WP attachment sizes

**Comment by moontear** [comment]
This was bugging me so I kind of did all the work already. Working flawlessly for me and better than ever (small image is loaded initially, larger images are being loaded after page load is finished). I used 
"Simple Image Sizes" to create some necessary width 9999, non-crop thumbnails. I'm already trying to get the small changes merged into justifiedGallery: https://github.com/miromannino/Justified-Gallery/pull/171

I tried making the whole thumbnails-from-wordpress into an extension, but I had to modify some core files (attachments & fields) hence maybe it is best you look at it and maybe collab on how to get this merged into foogallery? Just create a pull request and work from there?

**Core changes**
_class-foogallery-attachment.php_
- I believe attachments could definitely use the `sizes` field and it could go in main
- attachment attributes inside the `img` tag should be single quoted to JSON is possible

_class-gallery-metabox-fields.php_
- the `checkboxlist` isn't used anywhere and is kind of ugly with a pipe | in the identifier. I made it into a multilevel array, much easier to work with

**Justified Gallery changes**
_gallery-justified.php_
  - custom overrides for filters, maybe there's a better way?
  - include new settings

_class-justified-gallery-template.php_
  - new fields
  - get thumbs from WP filtered on width 9999/noncrop

_class-justified-gallery-overrides.php_
  - overrides for image attributes & WordPress thumb

_gallery-justified.js_
  - new version 3.6.2, de-minified as minification can be done later
  - added imgSizes to newSrc
  - get imgSizes from data-sizes
  - moved lastRow to settings
  - removed sizeRangeSuffixes
  - added thumbnailPath to generate URI for WP thumbs

I made branch with all changes here (and the working version):
https://github.com/moontear/foogallery/tree/feature/justified-gallery-wordpress-thumbnails

Part of the new settings:
![jg_settings_new](https://cloud.githubusercontent.com/assets/2392217/15891295/17c25130-2d9e-11e6-81ea-45920de81f8f.PNG)

**Comment by bradvin** [comment]
wow - this is really awesome! I will review your changes from your fork and test this out

Thanks for your contributions - it is really appreciated!

**Comment by bradvin** [comment]
I had a look at your proposed changes to the justified gallery: https://github.com/miromannino/Justified-Gallery/pull/171 and I am not sure these changes will be merged into the core plugin. They just seem too much of an edge-case for general usage. The reliance on data('sizes') seems very specific. Perhaps passing in the $image as the last parameter will be a more general solution that will then work for you and others with similar needs. Something like this:

`var newImageSrc = this.newSrc(imageSrc, imgWidth, imgHeight, $image);`

You can then change your function above to extract the sizes data attrib from the image object that is passed id:

`
thumbnailPath: (function(imageSrc, imgWidth, imgHeight, $image){

                var imgSizes = $image.data('sizes');

                if(!imgSizes) {
                  return imageSrc;
                }

                //remove extension (e.g. .jpg) and save to ext
                var ext, newImageSrc;
                var matchRes = imageSrc.match(/\.[^.\\/]+$/);
                if (matchRes !== null) {
                 ext = matchRes[0];
                 newImageSrc = imageSrc.replace(/\.[^.\\/]+$/, '');
                }

                //remove current suffix (e.g. -75x105) from default thumb
                newImageSrc = newImageSrc.replace(/-\d+x\d+$/, '');

                var imgSuffix = '';

                //get thumbnail corresponding most closely to desired height
                for (var i = 0; i < imgSizes.length; i++) {
                    imgSuffix = "-"+ imgSizes[i].width + "x" + imgSizes[i].height;
                  if (imgHeight <= imgSizes[i].height) {
                    break;
                  }
                }

                if ( imgSuffix != '' ) {
                  newImageSrc += imgSuffix + ext;
                } else {
                  newImageSrc += ext;
                }

                return newImageSrc;
               })
`

**Comment by moontear** [comment]
Love your thinking and you are perfectly correct. `$image` would also make it usable for other cases where one would one to fiddle around with the `thumbnailPath` function.
I already changed the pull request for justified gallery and my fork.

**Comment by bradvin** [comment]
cool - glad we agree on this :)

I will start a new feature branch on foogallery for this, which you can submit a pull request to. You have done the work, so it makes sense that you take the credit for the commits.

branch : https://github.com/fooplugins/foogallery/tree/feature%2Fjustified-gallery-images-sizes

**Comment by moontear** [comment]
Done. We can move the discussion over there then.

As I also wrote there:
- I'm not happy with the "overrides" and you may know better how to do this beautifully (in a more integrated way) with foogallery.
- While I personally believe WordPress thumbnails are "better" (as that's what they're made for) than WPThumb, I also believe it is harder for users to quickly generate the necessary thumbs - in this case width 9999 & noncrop. Another plugin might help here, but it certainly isn't as easy as just punching in a thumb height and WPThumb creating the thumb.
