### ISSUE TITLE
Control loading of foogallery assets

### ISSUE THREAD

**Issue by nickpish** [fooplugins/foogallery#69]
Hi, I'm using FooGallery with the FooBox (free) extension on a basic WordPress site, and I'm wondering about how to restrict the loading of all Foo-related assets to only the page(s) on which I'm actually including the gallery. I have one page called "Photos" which is the only one actually using the plugin, and yet I'm seeing the plugin-specific scripts and stylesheets loading on *all* pages in my site. I created a function to dequeue/deregister foobox scripts and styles in my `functions.php` theme file, but I'm assuming there must be a better way? Thanks for any feedback here.

**Comment by bradvin** [comment]
Hi @nickpish,

Assets enqueued by FooGallery are only added if the foogallery shortcode exists on the page.

I think you are referring to the assets that are enqueued by FooBox, as those are added by default.

FooBox PRO has a feature whereby you can decide not load FooBox assets by default, and then "opt-in" by means of a metabox on different post types.

**Comment by nickpish** [comment]
Hi @bradvin, thanks for your response. Yes, the "FooBox" assets are the ones I'm seeing on all pages-- so there's no easy way to disable loading of those without upgrading to the PRO version? Just trying to keep the overall payload to a minimum, especially on pages not using the plugin at all.

**Comment by bradvin** [comment]
You could hook into the wp_enqueue_scripts action with priority 99 and then dequeue the assets for all other pages

**Comment by nickpish** [comment]
@bradvin: I was able to successfully dequeue the primary `foobox-free-min` script and styles, but I'm still seeing a remaining FooBox script included in the markup body (which now causes an undefined object error in the console as the main script is no longer present) -- what else do I need to dequeue to effectively unregister all FooBox scripts? Thank you for your assistance here.

**Comment by lvvvvvl** [comment]
Hello,

Apologies if I'm hijacking this thread but I saw its fairly recent and it mentions an issue that is relevant to me.

I want to purchase Foobox Pro after reading this thread but after inquiring in the pre-sales forum [I was told that Foobox doesn't have the option](http://docs.fooplugins.com/support/topic/social-share-buttons-always-visible/) of 'not load assets by default' and instead I'll have to go through 1200 pages disabling the assets individually. 

So, just to confirm, even with the PRO version there's no way to universally disable the assets conditionally except for the pages that need them?

**Comment by bradvin** [comment]
@lvvvvvl - FooBox PRO has this feature.

This doc might help : http://docs.fooplugins.com/foobox/foobox-asset-loading/

**Comment by lvvvvvl** [comment]
@bradvin Awesome, I knew it sounded hard to believe it wasn't possible. You sir, know your stuff.

**Comment by bradvin** [comment]
@lvvvvvl you are hijacking this thread with yet another question. Also the questions are about FooBox and not FooGallery
