### ISSUE TITLE
Shortcode Enhancements

### ISSUE THREAD

**Issue by bradvin** [fooplugins/foogallery#73]
Enhancements to the foogallery shortcode:
- Ability to override gallery settings by passing parameters to shortcode. e.g.

`[foogallery gallery="456" thumb_size="200" lightbox="none" link="none"]`
- Ability to have shortcode work without creating a gallery first, e.g.

`[foogallery ids="1,2,3" template="masonry"]`
- Ability to have shortcode work without any parameters. The gallery will pull in all defaults set in the FooGallery settings. All attachment images attached to the post will be used as the source of images. e.g.

[foogallery]

**Comment by bradvin** [comment]
https://wordpress.org/support/topic/display-only-single-or-3-newest-pictures-from-foogallery

perhaps a "limit" argument can be used in the shortcode

**Comment by Blutreiter** [comment]
A limited amount of pictures would be great.
Another sensible addition would be a random argument, which would enable to display a random picture from a gallery.

Arguments like that make a great preview tool for gallery page links, especially when the galleries get updated regularly, without manually fiddling each time.

**Comment by leowski** [comment]
Hi bradvin. Some arguments like "limit", "template" and others would be great! You plan to add them soon? Thanks

**Comment by markhankins** [comment]
I was convinced I'd used this shortcode parameter before with foogallery?  Maybe I was mistaken?  It would be awesome if we could limit from within the shortcode though!

**Comment by imber21** [comment]
Limit would definitely be useful! This is what I'm currently using for a project:

`add_filter('foogallery_attachment_get_posts_args', 'kt_foogallery_query');`

```php
function kt_foogallery_query($args) {
	global $current_foogallery_arguments;
	$limit = $current_foogallery_arguments['limit'];
	if (!empty($limit)) {
		$args['posts_per_page'] = $limit;
	}
	return $args;
}
```

Which filters the query used in `FooGalleryDatasource_MediaLibrary`.

**Comment by 5vbz3r0** [comment]
I would definitely love to see a 'limit' argument.

**Comment by bradvin** [comment]
this is available at the moment - https://fooplugins.helpscoutdocs.com/article/132-shortcode-attributes

**Comment by Choccanet** [comment]
I would love to be able to display the latest pictures from all galleries in a widget or with a shortcode.
