### ISSUE TITLE
Remove wp_get_attachment_image_src

### ISSUE THREAD

**Issue by developer-lindner** [fooplugins/foogallery#75]
Why are you using this old function call for gallery attachments?
But for the featured image the right one?

It's 2016 now, not 1990.... please add or change it to use wp_get_attachment_image
so that anyone can use responsive images.

**Comment by bradvin** [comment]
is it 2016? Wow - thanks for pointing that out

**Comment by developer-lindner** [comment]
Sorry, should sound harsh... just joking ;)
Would be pretty nice to have it to built better reponsive themes and stuff.

Great plugin anyway!
