### ISSUE TITLE
Ability to use original thumbs

### ISSUE THREAD

**Issue by bradvin** [fooplugins/foogallery#76]
Include a setting called "Use Original Thumbnails",
which by default is disabled,
that allows the thumb generation in foogallery to check for the default WP thumbs and use those if available

**Comment by bradvin** [comment]
feature can be tested from the branch https://github.com/fooplugins/foogallery/tree/feature/use_original_thumbnails

**Comment by rlxmp** [comment]
I know this is very old, but would like to inquire about using original images also for the retina version when enabled. My reason for using original images is to get a SEO friendly filename for the thumbnail image. When not using original images, it's just a cache number.jpg. I create the exact image size with Meow Apps Perfect Images.

Not 100% sure if this would help SEO, but seeing that google image bot crawls this cache folder all the time it seems it would..
