### ISSUE TITLE
Caption spacing

### ISSUE THREAD

**Issue by nmcreative** [fooplugins/foogallery#78]
I don't so much mind the spacing between the caption title and the description, but when the title goes to a second line, it has the same amount of spacing which is way too much. http://healtheplanet.com/photo-gallery/

Is there any way to edit the spacing between the lines of text?

**Comment by bradvin** [comment]
Hi

Your theme's CSS is causing the issue (http://healtheplanet.com/wp-content/themes/reviver/css/plugins.css?ver=4.5.3 line 3461)

Add this custom CSS to your gallery:

.foogallery-thumbnail .thumbnail-caption h3 {
    line-height: normal;
}

**Comment by nmcreative** [comment]
Thank you!! Worked like a charm!



Nina Anderson
Graphic Artist
www.ninamariecreative.com <http://www.ninamariecreative.com/>
