### ISSUE TITLE
Thumbnails are blurry

### ISSUE THREAD

**Issue by rsettino** [fooplugins/foogallery#81]
Hello, 

The thumbnails generated from the gallery have a blurry quality to it. We would love to get the images clearer. This is a link to the gallery:
http://www.jgmerzon.com/portfolio/
We have the latest version of Food Gallery 1.2.12. Help?

Thanks,
Robyn

**Comment by bradvin** [comment]
your website is under construction and I cannot access the gallery.

**Comment by rsettino** [comment]
I apologize about that! You can now view the gallery.

**Comment by bradvin** [comment]
thanks - I can see your page now - which thumbs are blurry for you?
I had a look and they seem to look fine. What is your thumb quality set to in your settings?

**Comment by rsettino** [comment]
The thumbnail quality is set to 100. The website is a friend's. She is an artist and these are her paintings. When I first looked at the gallery I thought they looked fine as well but when you click on the image and it opens up you can see how much sharper and clearer it is. Do you think there is anything that can be done to make the thumbnails look at sharp as the bigger photos?

**Comment by bradvin** [comment]
unfortunately not - as the thumb generation is ultimately done via php extensions on the server.
You could always opt for bigger thumb sizes?

**Comment by rsettino** [comment]
Ah ok - I will pass this on to her. Thank you!
