### ISSUE TITLE
$args['link'] = 'none'; for attachments still results in an anchor being output around images

### ISSUE THREAD

**Issue by mathetos** [fooplugins/foogallery#84]
In troubleshooting a bug in the Zoom and Owl templates, a change made in version 1.2.10 results in the $args['link'] = 'none' from $attachment->html($args) not being respected. 

While setting this argument does actually remove the href from the anchor tag, it leaves the anchor tag present. This is problematic for templates like ZOOM which have a custom markup, but want to use the other arguments of the attachment html output.

**Comment by mathetos** [comment]
As an example, with the ZOOM gallery, before version 1.2.10 I output the images with the following markup:
`echo '<div class="magnify" id="' . $attachment->ID . '"><div class="large"  style="background: url(' . $attachment->url . ') no-repeat;" data-url="' . $attachment->url . '"></div>' . $attachment->html( $args, true, false ) . '</div>';`

But after 1.2.10 I have to output the image tag directly, which I believe will limit how effectively I can use other aspects of FooGalleries features (though testing this so far is working fine):

`echo '<div class="magnify" id="' . $attachment->ID . '"><div class="large"  style="background: url(' . $attachment->url . ') no-repeat;" data-url="' . $attachment->url . '"></div><img src="' . $attachment->url . '" class="small" width="' . $attachment->width . '" height="' . $attachment->height . '"></div></div>';`

**Comment by bradvin** [comment]
@mathetos have you tried $attachment->html_img( $args );

**Comment by mathetos** [comment]
That worked perfectly. Thanks!
