### ISSUE TITLE
Bug: Media modal always opens first selection

### ISSUE THREAD

**Issue by nateinaction** [fooplugins/foogallery#86]
Steps to recreate:
1. In Edit Gallery view click the "i" Edit info button on any photo.
2. Close the media modal and then click the "i" Edit info button on a different photo.
Result: the media modal will always open to the first photo selected.

The quickest fix is to remove the following lines from admin-foogallery.js
`if ( FOOGALLERY.media_uploader !== false ) {
    // Open frame
    FOOGALLERY.media_uploader.open();
    return;
}`

Deleting this statement does mean that when a user closes the media modal during a multi-select operation that their selection will not be saved. Please let me know your thoughts!

**Comment by nateinaction** [comment]
Seeking comment on this. Is there a better way to fix the edit info button?

**Comment by bradvin** [comment]
Hi Nate
Your solution seems to be logically correct, but I would need to investigate it a bit more before I could say for certain.
