### ISSUE TITLE
Masonery not working properly with 4.6

### ISSUE THREAD

**Issue by LGphoto** [fooplugins/foogallery#88]
Here is a print of the problem: http://www.lgphotography.fr/Help/PbFooGallery.jpg
The pictures are covering each other.

Settings:
Masonery image Gallery
Thumbnail width: 400
Masonery Layout: Fixed Width
Gutter width: 10
Image alignment: Center
Theme Twenty Twelve

I am now mooving gutter width to 30 to have a less messed up site, but it leave an ugly bigger vertical space...

**Comment by bradvin** [comment]
This seems to be a CSS conflict, as the Twenty Twelve theme now includes a style for content images to use a max-width:100% which conflicts with the way masonry calculates it's column widths. The quickest solution is to add this custom CSS to your galleries:

`
.foogallery-masonry .item a img {
    max-width: inherit;
}
`

I will include this CSS in the next version of Foo Gallery. I tested this fix in dev tools on your site and it fixed the problem with gutter width of 10px. Let me know if it solves it for you

**Comment by LGphoto** [comment]
Thank you for your answer and for your help.
I have tried to add this to the galleries' custom CCS and it didn't work.
Then I have tried as well to copy it in the site's CCS Edit and had no result either...
There is nothin about image on my custom CCS, but I'll copy it here anyway in case you think there could be a conflict:
`/*__________ Mint Cream Flavor child twentytwelve __________*/
	
}

footer[role="contentinfo"] {
	border: 0;
	padding-top: 48px;
}

body .site {
	margin: 0;
	padding: 0;
	box-shadow: none;
}

.site-content article {
	margin-bottom: 24px;
}

.wrapper {
	margin-top: 12px;
}

.site-header hgroup, .site-header nav, .wrapper, footer[role="contentinfo"] .site-info {
	padding-left: 10px;
	padding-right: 10px;
}

@media screen and (min-width: 600px) {
	.site-header {
		padding: 4px 0 0;
	}
	
	.main-navigation ul.nav-menu, .main-navigation div.nav-menu > ul {
		border: 0;
	}
	
	.wrapper {
		margin-top: 2px;
	}
	
	body .site, footer[role="contentinfo"] {
		max-width: 100%;
	}
	
	.site-header hgroup, .site-header nav, .wrapper, footer[role="contentinfo"] .site-info {
		margin-left: auto;
		margin-right: auto;
		max-width: 920px;
		padding-left: 20px;
		padding-right: 20px;
	}
}

@media screen and (min-width: 960px) {
	.site-header hgroup, .site-header nav, .wrapper, footer[role="contentinfo"] .site-info {
		max-width: 940px;
		padding-left: 0;
		padding-right: 0;
	}
}

@media screen and (min-width: 980px) {
	.site-header hgroup, .site-header nav, .wrapper, footer[role="contentinfo"] .site-info {
		max-width: 960px;
	}
}

/*__________ end Mint Cream adjustments __________*/
/*__________ Couleur du menu deroulant (liens) __________*/
.main-navigation li ul li a {
	background: rgba(255,255,255,0.85) none repeat scroll 0 0;
	border-bottom: 1px solid #B6B6B6;
	display: block;
	font-size: .785714rem;
	line-height: 2.18182;
	padding: .571429rem .714286rem;
	width: 12.8571rem;
	white-space: normal;
}

/*__________ Fin Couleur du menu deroulant (liens) __________*/
a {
	outline: medium none;
	color: #636363;
}

/*__________ Taille champs Forulaire de contact Contact Form 7 __________*/
input[type="textarea"], textarea {
	width: 100%;
}

/*__________ Fin Taille champs Forulaire de contact Contact Form 7 __________*/
.widget img, img.header-image, .author-avatar img, img.wp-post-image {
	box-shadow: none;
}

/*__________ Réduire espace au dessus de la barre de menu __________*/
.main-navigation {
	margin-top: 0;
}

/*__________ Fin Réduire espace au dessus de la barre de menu __________*/
/*__________ Réduire taille de la barre de menu petit écran__________*/
@media screen and (max-width: 960px) {
	.nav-menu a {
		font-size: 80%;
	}
}

/*__________ Fin Réduire taille de la barre de menu petit écran__________*/`

Another solution (which may be even better), if possible, would be to get the 2 or 3 colmuns layout to center in the page...

**Comment by LGphoto** [comment]
I have left this setup for an extra gallery which has no link on my site, so few peopole may access, in case you need to check it: http://www.lgphotography.fr/track-day-interlagos-24012016/interlagos-24012016-marcas-e-pilotos-classicos-da-competicao/
(sorry, it is a lot o pictures)

**Comment by bradvin** [comment]
please can you try the latest code from the master branch to see if that resolves your issue
