### ISSUE TITLE
foolic_update_checker_v1_5 uses PHP4 style constructor

### ISSUE THREAD

**Issue by Shelob9** [fooplugins/foogallery#89]
This throws deprecation notice in PHP7.

**Comment by lkraav** [comment]
http://docs.fooplugins.com/support/topic/php7-incompatibility-spams-debug-log/

Haven't checked whether they actually did anything.

**Comment by bradvin** [comment]
there is no foolic_update_checker file in foogallery codebase

**Comment by Shelob9** [comment]
@bradvin I just checked, the notice was being thrown from the FooVideo and FooBox. So wrong repo I will close. For the record, I am using:

FooBox: 2.3.2.30
FooGallery Video Extension 1.0.7
