### ISSUE TITLE
Images overlap in Masonry layout upon window resize

### ISSUE THREAD

**Issue by seanbarney** [fooplugins/foogallery#90]
Hello. Using a gallery with the following settings:

Gallery template: "Masonry Image Gallery"
Masonry layout of: "Fixed Width"
Image alignment: "Center Alignment"

All other settings to their default.

When loading the gallery in a page it looks fantastic. However when resizing the window, the images start will lose their arrangement and start overlapping each other.

Any suggestions on how to maintain the integrity of the gallery during window resizes?

**Comment by bradvin** [comment]
hey. Can you link to you gallery please.
I have setup a demo using your settings here : http://foo.gallery/demos/masonry-big-thumbs/
And I cannot reproduce your overlapping issue.

Perhaps there is a CSS conflict of sorts

**Comment by seanbarney** [comment]
Hi bradvin  -- your demo does seem to be working properly.

Here's the link to my gallery which is still having the issue:  http://moaboutmo.com/style/

Thank you!
