### ISSUE TITLE
Images are blurry on iPhone

### ISSUE THREAD

**Issue by a4jp-com** [fooplugins/foogallery#91]
All the images are blurry on my iPhone.

Can more than one image be shown on a mobile phone? There is too much scrolling now. My PC site looks great though.

**Comment by a4jp-com** [comment]
Is there an easy way to fix this or do we have to buy another plugin for the retina images?

**Comment by bradvin** [comment]
This should be resolved now using the retina options for a gallery in 1.2.17

**Comment by a4jp-com** [comment]
Thank you ^^

**Comment by a4jp-com** [comment]
I just checked your demo page but the magnify glass is pixelated.
