### ISSUE TITLE
Yoast sitemap and foogallery

### ISSUE THREAD

**Issue by fraiquin** [fooplugins/foogallery#92]
Hi, I use the Foogallery on some of my project pages – I use the Yoast sitemap function, and creates a sitemap-index.xml file /page and /category sitemaps work fine - but the one called: /project-sitemap.xml I get this error:

Fatal error: Call to a member function attachments() on a non-object in:
wp-content/plugins/foogallery/includes/public/class-yoast-seo-sitemaps.php on line 30

Any ideas?
Many thanks.

Also posted on WP support thread

**Comment by bradvin** [comment]
yoast seo plugin might have changed in a recent update. I will investigate. Thanks for letting me know

**Comment by bradvin** [comment]
After some investigation I found the problem. When you have deleted a gallery, then the sitemap breaks with a fatal error. Adding in some checks https://github.com/fooplugins/foogallery/commit/4891df4cc07edc48434faac1a246b04af9a584a4 fixes the problem

**Comment by fraiquin** [comment]
Hi, I've updated the plugin, disabled and then re-enabled XML sitemaps, but I'm still gettin gthe same error on the same sitemap.

**Comment by bradvin** [comment]
I also found that the sitemaps are cached, so you might need to update a page in order to get them to regenerate

**Comment by fraiquin** [comment]
I've updated all pages and projects and foogalleries on my site, but I'm still getting that error on that particular sitemap.

**Comment by bradvin** [comment]
how did you update the plugin? Did you download the latest zip from github and upload it?

**Comment by fraiquin** [comment]
I updated it through the wordpress update screen. 1.2.15 version.

**Comment by bradvin** [comment]
OK! That version does not have the fix yet. Download here : https://github.com/fooplugins/foogallery/archive/master.zip

**Comment by fraiquin** [comment]
Wonderful - sorry I hadn't realised I should download from Github. Works perfectly now. Thanks for great support.
