### ISSUE TITLE
Crash IE11

### ISSUE THREAD

**Issue by leonardorotundo** [fooplugins/foogallery#95]
Plugin crash in IE11 can you see it?
www.delfinoglobal.com

**Comment by bradvin** [comment]
I went to your site in IE11 and it did not crash. What do you mean by crash exactly? Also, I could not actually find a foogallery at the link you provided

**Comment by leonardorotundo** [comment]
I mean that i can't see the gallery at the top of each page if you visit the site in chrome you will see, thanks
