### ISSUE TITLE
Foobox free lightbox not working

### ISSUE THREAD

**Issue by waynehoover** [fooplugins/foogallery#96]
Foobox free is installed and selected for a gallery and links don't open in a lightbox. Any idea why?

**Comment by bradvin** [comment]
Hard to tell, but I do not think it is a problem with FooGallery, but rather a conflict when using the FooBox plugin with your theme. Share a link to your site.

**Comment by waynehoover** [comment]
Hi yes it was, wasn't calling `wp_footer();`
