### ISSUE TITLE
[Enhancement] Lazy Load

### ISSUE THREAD

**Issue by lunacroft** [fooplugins/foogallery#98]
Add lazy load to galleries would be very useful.

**Comment by onerock** [comment]
I agree that this would be a good addition or resolving the issue that FooGallery ver 1.2.9 caused.  I believe that currently no lazy load plugins work with FooGallery.  [WordPress Ticket](https://wordpress.org/support/topic/plugin-conflict-with-foogallery-plugin/#post-8397802)

**Comment by devth** [comment]
+1, my client has nearly 300 images in their FooGallery so an "infinite scroll" type lazy loader would improve the UX a ton!

**Comment by m-pawelczyk** [comment]
Will BJ Lazy Load works with FooGallery as current fix?

https://wordpress.org/plugins/bj-lazy-load/

**Comment by brit77** [comment]
@m-pawelczyk BJ Lazy Load did not work with FooGallery for me. It seemed to mess up the thumbnails in the gallery.

I also would like to see this enhancement, to make FooGallery lazy loadable or compatible with lazy load plugins. For now, I've advised my client to reduce the number of images in her gallery to improve loading.

**Comment by bradvin** [comment]
@brit77 this is definately on the cards for a future release. It will be built in

**Comment by jhit** [comment]
Any news on this feature. Really needing it. make it a pro feature and I will opt-in.
